version: '3'

services:

  database:
    image: postgres:latest
    volumes:
      - database_volume:/var/lib/postgresql/data
    # env_file:
    #   - config/db/database_env
    environment:
      - POSTGRES_USER=uttu
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=backend
    networks:
      - database_network

  # web container, with django + gunicorn
  djangoapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - static:/backend/static
      - media:/backend/media
    networks:
      - database_network
      - nginx_network
    depends_on:
      - database
    # command: "python manage.py migrate"


  # reverse proxy container (nginx)
  nginx:
    image: nginx:1.23.4
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/backend/static
      - media:/backend/media
    networks:
      - nginx_network
    depends_on:
      - djangoapp
      - database

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  static:
  media:
  database_volume: