name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build --if-present

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./build/*"
        REMOTE_HOST: 143.110.146.79
        REMOTE_USER: root
        TARGET: /var/www/test/
        SCRIPT_AFTER: |
          sudo nginx -t && sudo systemctl restart nginx
