name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build --if-present



    # - name: Restart Apache
    #   run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@143.110.146.79 "ls"
    
    # - name: SSH into Droplet & Git pull & restart Droplet
    #   uses: appleboy/ssh-action@v0.1.8
    #   with:
    #     host: 143.110.146.79
    #     username: root
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     port: 22
    #     script: |
    #       ls

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./build/*"
        REMOTE_HOST: 143.110.146.79
        REMOTE_USER: root
        TARGET: /var/www/test/
        # EXCLUDE: "/dist/, /node_modules/"
        # SCRIPT_BEFORE: |
        #   whoami
        # SCRIPT_AFTER: |
        #   cd /var/www/html/
        #   pwd
