name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main
    pull_request:
    branches: 
      - main
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: npm install

    # - name: Build app
    #   run: npm run build

    # - name: Copy files to Droplet
    #   run: scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ./build/* <USERNAME>@<DROPLET_IP_ADDRESS>:/var/www/html/

    - name: Restart Apache
      run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@143.110.146.79 "ls"
