name: Validation_Gauntlet

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install virtualenv
      run: pip install virtualenv

    - name: Create virtual environment
      run: virtualenv venv

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

  # lint:
  #   runs-on: ubuntu-latest
  #   needs: install

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Python
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: 3.x

  #   - name: Restore virtual environment from cache
  #     uses: actions/cache@v3
  #     with:
  #       path: venv
  #       key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
  #       restore-keys: |
  #         ${{ runner.os }}-venv-
  #   - name: Activate virtual environment
  #     run: |
  #       source venv/bin/activate

  #   - name: Install flake8
  #     run: pip install flake8
    
  #   - name: Lint code
  #     run: |
  #       flake8 .

  build:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Restore virtual environment from cache
      uses: actions/cache@v3
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Activate virtual environment
      run: source venv/bin/activate

    - name: check if django fetched or not
      run: |
        python3 
        import django
        django.VERSION

    # - name: Install dependencies
    #   run: pip install -r requirements.txt

    - name: Make log files folder 
      run: mkdir log_files
      
    - name: Build project
      run: |
        python manage.py check