name: Create a comment on new issues

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:


jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet & Git pull & restart Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/backend/BioVatika-Backend
            git pull https://${{secrets.USERNAME_GITHUB}}:${{secrets.ACCESS_TOKEN}}@github.com/Relish-Repo/BioVatika-Backend.git develop
            source ../venv/bin/activate
            pip -V
          # pip install -r "requirements.txt"
          # python3 manage.py migrate
          # sudo systemctl restart gunicorn
          # sudo systemctl daemon-reload
          # sudo systemctl restart gunicorn.socket gunicorn.service
          # sudo nginx -t && sudo systemctl restart nginx
