name: Create a comment on new issues

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:


jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 178.128.198.31
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/backend/BioVatika-Backend
            ls
      # git pull https://biohazard2117:${{secrets.ACCESS_TOKEN}}@github.com

      # - name: Go to working directory
      #   run: cd /var/www/backend/BioVatika-Backend
      #   shell: bash

      # - name: git pull latest code
      #   run: |
      #     pwd
      #     git pull

